name = input()
num = input()
x = input ()
y = input ()
z = input ()
sum = int(x) + int(y) + int(z)

print('Name:',name,sep='')
print('Id:',num,sep='')
print('Total:',sum,sep='')
print('Average:',sum // 3,sep='')
